### ISSUE TITLE
Suggestion: Responsive UI

### ISSUE THREAD

**Issue by lingbopro** [Minemetero/Table-Tennis-Counter#16]
这个UI在移动端有点小问题  
需要进行响应式设计  
比如当视口大小较窄时切换到竖向布局  

附截图：  
![Screenshot_20240623_103127_com.microsoft.emmx.jpg](https://github.com/Minemetero/Table-Tennis-Counter/assets/148617407/813de4a9-937a-4852-9b56-b4e55e3d1b29)

**Comment by Minemetero** [comment]
真奇怪

**Comment by Minemetero** [comment]
怎么会有想要在手机上用

**Comment by lingbopro** [comment]
> 怎么会有想要在手机上用

毕竟也不是每个乒乓球桌都有电脑和大屏幕（

**Comment by Minemetero** [comment]
我现在有点事，等下研究

**Comment by lingbopro** [comment]
其实不难，计分界面用的是flex布局，只需要加一个`@media`标签，当视口宽度小于指定值时把`flex-direction`设成`column`即可

**Comment by lingbopro** [comment]
已经测试过了，核心代码就这么简单：

```css
@media screen and (max-width: 700px) {
    #gameBoard {
        flex-direction: column;
    }
}
```
